spring:
  datasource:
    username: root
    password: a4345198@
    url: jdbc:mysql://120.48.44.19:3306/mall-pms
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 120.48.44.19:8848
    alicloud:
      access-key: LTAI5tAC9N6Mf63EpjcxU56n
      secret-key: PugSsby1mpvPRdIkvNRd4VpyTgB2zy
      oss:
        endpoint: https://oss-cn-chengdu.aliyuncs.com

  application:
    name: mall-product
  # 设置服务器相应给客户端的日期时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0
server:
  port: 8040